-- RLS sur les tables créées directement dans Supabase (sans migration)
-- ALTER TABLE ... ENABLE ROW LEVEL SECURITY est idempotent

ALTER TABLE clients       ENABLE ROW LEVEL SECURITY;
ALTER TABLE devis         ENABLE ROW LEVEL SECURITY;
ALTER TABLE paiements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE attestations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE chiffres      ENABLE ROW LEVEL SECURITY;
ALTER TABLE contenus      ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipe        ENABLE ROW LEVEL SECURITY;
ALTER TABLE parametres    ENABLE ROW LEVEL SECURITY;
ALTER TABLE realisations  ENABLE ROW LEVEL SECURITY;
ALTER TABLE services      ENABLE ROW LEVEL SECURITY;
ALTER TABLE temoignages   ENABLE ROW LEVEL SECURITY;
